title: "StudentConnect"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "ZAY2526S1-CS2103T-T14-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
